#!/usr/bin/env python3
"""
Script to analyze and visualize trading signals generated by ICT bot for August 2024.
"""

import pandas as pd
from datetime import datetime
from collections import defaultdict
import json

def load_signals_from_bot():
    """Run ict_bot.py and capture the signals"""
    import sys
    sys.path.insert(0, '/home/runner/work/ict-trading-bot/ict-trading-bot')
    
    from ict_bot import load_data, generate_signals
    
    print("Loading data and generating signals...")
    m15, h4, d1, w1, m1 = load_data()
    signals = generate_signals(m15, h4, d1, w1, m1)
    
    return signals, m15

def analyze_signals(signals, m15_data):
    """Analyze the generated signals"""
    
    if not signals:
        print("No signals to analyze!")
        return
    
    print(f"\n{'='*80}")
    print(f"ICT TRADING BOT - BACKTEST RESULTS FOR AUGUST 2024")
    print(f"{'='*80}\n")
    
    # Convert signals to DataFrame for easier analysis
    df_signals = pd.DataFrame(signals)
    
    # Basic statistics
    total_signals = len(signals)
    print(f"📊 OVERALL STATISTICS")
    print(f"{'─'*80}")
    print(f"Total signals generated: {total_signals}")
    
    # Direction breakdown
    if 'direction' in df_signals.columns:
        direction_counts = df_signals['direction'].value_counts()
        print(f"\n📈 SIGNAL DIRECTION:")
        for direction, count in direction_counts.items():
            percentage = (count / total_signals) * 100
            print(f"  • {direction}: {count} ({percentage:.1f}%)")
    
    # Session breakdown
    if 'session' in df_signals.columns:
        session_counts = df_signals['session'].value_counts()
        print(f"\n🕐 SIGNALS BY SESSION:")
        for session, count in session_counts.items():
            percentage = (count / total_signals) * 100
            print(f"  • {session.capitalize()}: {count} ({percentage:.1f}%)")
    
    # Analyze by date
    df_signals['date'] = pd.to_datetime(df_signals['datetime']).dt.date
    signals_by_date = df_signals.groupby('date').size()
    
    print(f"\n📅 SIGNALS BY DATE:")
    print(f"  • Most active day: {signals_by_date.idxmax()} ({signals_by_date.max()} signals)")
    print(f"  • Least active day: {signals_by_date.idxmin()} ({signals_by_date.min()} signals)")
    print(f"  • Average signals per day: {signals_by_date.mean():.1f}")
    
    # Top 5 most active days
    print(f"\n  Top 5 most active trading days:")
    for i, (date, count) in enumerate(signals_by_date.nlargest(5).items(), 1):
        print(f"    {i}. {date}: {count} signals")
    
    # Condition analysis
    print(f"\n🔍 SIGNAL CONDITIONS ANALYSIS:")
    conditions_summary = defaultdict(int)
    
    for signal in signals:
        if 'conditions' in signal:
            for condition, value in signal['conditions'].items():
                if value:
                    conditions_summary[condition] += 1
    
    for condition, count in sorted(conditions_summary.items(), key=lambda x: x[1], reverse=True):
        percentage = (count / total_signals) * 100
        print(f"  • {condition}: {count} times ({percentage:.1f}%)")
    
    # Show sample signals from different sessions
    print(f"\n{'='*80}")
    print(f"📋 SAMPLE SIGNALS (First 15):")
    print(f"{'='*80}\n")
    
    for i, signal in enumerate(signals[:15], 1):
        dt = signal['datetime']
        session = signal.get('session', 'N/A')
        direction = signal.get('direction', 'N/A')
        price = signal.get('price', 0)
        
        print(f"{i:2d}. {dt} | {session.upper():8s} | {direction:5s} @ {price:.5f}")
        
        # Show conditions
        if 'conditions' in signal:
            conditions = [k for k, v in signal['conditions'].items() if v]
            if conditions:
                print(f"    Conditions: {', '.join(conditions)}")
        print()
    
    # Show signals from each session
    print(f"\n{'='*80}")
    print(f"📋 SAMPLE SIGNALS BY SESSION:")
    print(f"{'='*80}\n")
    
    for session in ['asia', 'frankfurt', 'london', 'new_york']:
        session_signals = [s for s in signals if s.get('session') == session]
        if session_signals:
            print(f"\n{session.upper()} SESSION ({len(session_signals)} signals):")
            for i, signal in enumerate(session_signals[:3], 1):
                dt = signal['datetime']
                direction = signal.get('direction', 'N/A')
                price = signal.get('price', 0)
                print(f"  {i}. {dt} | {direction:5s} @ {price:.5f}")
    
    # Price range analysis
    print(f"\n{'='*80}")
    print(f"💰 PRICE RANGE DURING AUGUST 2024:")
    print(f"{'='*80}")
    print(f"  • Starting price (Aug 1):  {m15_data.iloc[0]['Close']:.5f}")
    print(f"  • Ending price (Aug 31):   {m15_data.iloc[-1]['Close']:.5f}")
    print(f"  • Highest price:           {m15_data['High'].max():.5f}")
    print(f"  • Lowest price:            {m15_data['Low'].min():.5f}")
    
    price_change = m15_data.iloc[-1]['Close'] - m15_data.iloc[0]['Close']
    price_change_pct = (price_change / m15_data.iloc[0]['Close']) * 100
    print(f"  • Total price change:      {price_change:.5f} ({price_change_pct:.2f}%)")
    
    # Save summary to file
    summary = {
        "total_signals": total_signals,
        "date_range": f"{df_signals['datetime'].min()} to {df_signals['datetime'].max()}",
        "signals_by_direction": direction_counts.to_dict() if 'direction' in df_signals.columns else {},
        "signals_by_session": session_counts.to_dict() if 'session' in df_signals.columns else {},
        "most_active_day": str(signals_by_date.idxmax()),
        "conditions_frequency": dict(conditions_summary)
    }
    
    with open('backtest_summary.json', 'w') as f:
        json.dump(summary, f, indent=2, default=str)
    
    print(f"\n{'='*80}")
    print(f"✅ Analysis complete! Summary saved to backtest_summary.json")
    print(f"{'='*80}\n")

def main():
    """Main analysis function"""
    signals, m15_data = load_signals_from_bot()
    
    if not signals:
        print("⚠️  No signals were generated. The strategy conditions may be too strict.")
        print("Consider adjusting the parameters in ict_bot.py")
        return
    
    analyze_signals(signals, m15_data)

if __name__ == "__main__":
    main()
